'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DTL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property chemsep1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chemsep1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property csid() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("csid", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property dwsim() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dwsim", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Henry() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Henry", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property joback() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("joback", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property kij_pr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kij_pr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property kij_srk() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kij_srk", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property lkp_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lkp_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property modfac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("modfac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property modfac_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("modfac_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property NIST_MODFAC_IP() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NIST_MODFAC_IP", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property NIST_MODFAC_RiQi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NIST_MODFAC_RiQi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property nrtl() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nrtl", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property pcsaft() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pcsaft", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property pcsaft_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pcsaft_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property pr_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pr_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property prsv2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("prsv2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property prsv2_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("prsv2_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property prsv2_ip_vl() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("prsv2_ip_vl", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property srk_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("srk_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property unifac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unifac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property unifac_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unifac_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property unifac_ll_ip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unifac_ll_ip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property uniquac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("uniquac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property uniquacip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("uniquacip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
